import { Permission } from '@vendure/core';

export const TENANT_ADMIN_PERMISSIONS = [
    Permission.ReadCatalog,
    Permission.CreateCatalog,
    Permission.UpdateCatalog,
    Permission.DeleteCatalog,
    Permission.ReadCustomer,
    Permission.CreateCustomer,
    Permission.UpdateCustomer,
    Permission.ReadOrder,
    Permission.UpdateOrder,
    Permission.ReadPromotion,
    Permission.CreatePromotion,
    Permission.UpdatePromotion,
    Permission.DeletePromotion,
    Permission.ReadSettings,
    Permission.CreateChannel,
    Permission.ReadChannel,
    Permission.UpdateChannel,
    Permission.ReadShippingMethod,
    Permission.CreateShippingMethod,
    Permission.UpdateShippingMethod,
    Permission.ReadPaymentMethod,
    Permission.ReadAdministrator,
    Permission.CreateAdministrator,
    Permission.UpdateAdministrator,
    Permission.ReadAsset,
    Permission.CreateAsset,
    Permission.UpdateAsset,
    Permission.DeleteAsset,
];
